[project]
name = "mome-plus"
version = "0.1.0"
requires-python = ">=3.9"
description = "MoME+ (Mixture of Medical Experts) - Multi-modal brain tumor segmentation based on nnU-Net."
readme = "readme.md"
license = { file = "LICENSE" }
authors = [
    { name = "Xinru Zhang" },
    { name = "Fabian Isensee", email = "f.isensee@dkfz-heidelberg.de"},
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Healthcare Industry",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
]
keywords = [
    'deep learning',
    'image segmentation',
    'brain tumor',
    'multi-modal',
    'mixture of experts',
    'nnU-Net',
]
dependencies = [
    "torch>=2.0.0",
    "acvl-utils>=0.2",
    "tqdm",
    "scipy",
    "batchgenerators>=0.25",
    "numpy",
    "scikit-learn",
    "scikit-image>=0.19.3",
    "SimpleITK>=2.2.1",
    "pandas",
    "nibabel",
    "yacs",
    "matplotlib",
    "seaborn",
]

[tool.setuptools.packages.find]
include = ["nnunetv2*", "dynamic_network_architectures*"]

[project.urls]
homepage = "https://github.com/ZhangxinruBIT/MoME"

[project.scripts]
mome_predict = "nnunetv2.inference.predict_from_raw_data:predict_entry_point_modelfolder"
